name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - entw
  workflow_dispatch:  # <--- DIESE ZEILE ERZWINGT DEN BUTTON

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Main Branch
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_MAIN }}
          password: ${{ secrets.FTP_PASSWORD_MAIN }}
          server-dir: ./
          security: loose

      - name: Deploy to Entw Branch
        if: github.ref == 'refs/heads/entw'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_ENTW }}
          password: ${{ secrets.FTP_PASSWORD_ENTW }}
          server-dir: ./
